### ISSUE TITLE
The bot has stopped working

### ISSUE THREAD

**Issue by tocacyy** [lmusarella/PCS-Prediction-V2#31]
I've tried all the variants I knew: I deleted and reinstalled the bot, but it still does the same thing. I tried other strategy variations, and it still does the same, I changed the link from the BSC_RPC node, and there is no change.

⏰ Waiting for next round: 216217
====================================================================
⚔️  ROUND: 216217 | ⌚ 16:29 | START 🎉
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  ✔️  Current Profit: 0 USD = 0 BNB
  ✔️  Current Balance: 129.259 USD = 0.61207 BNB
  ⏰ Waiting 3.4 minutes before execute SIGNAL_STRATEGY
====================================================================
⚔️  ROUND: 216218 | ⌚ 16:34 | START 🎉
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  ✔️  Current Profit: 0 USD = 0 BNB
  ✔️  Current Balance: 129.35 USD = 0.61207 BNB
  ⏰ Waiting 3.4 minutes before execute SIGNAL_STRATEGY
====================================================================
♻️  Skip round: 216218
🚨 Bot is running in Martingale Mode! Waiting pending rounds: [216217] - if some rounds remain hanging, they will be eliminated after 2 rounds.
====================================================================
⚔️  ROUND: 216219 | ⌚ 16:39 | START 🎉
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  ✔️  Current Profit: 0 USD = 0 BNB
  ✔️  Current Balance: 129.175 USD = 0.61207 BNB
  ⏰ Waiting 3.4 minutes before execute SIGNAL_STRATEGY
====================================================================
♻️  Skip round: 216219
🚨 Bot is running in Martingale Mode! Waiting pending rounds: [216217] - if some rounds remain hanging, they will be eliminated after 2 rounds.
====================================================================
⚔️  ROUND: 216220 | ⌚ 16:44 | START 🎉
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  ✔️  Current Profit: 0 USD = 0 BNB
  ✔️  Current Balance: 129.111 USD = 0.61207 BNB
  ⏰ Waiting 3.4 minutes before execute SIGNAL_STRATEGY
====================================================================
⚔️  ROUND: 216221 | ⌚ 16:49 | START 🎉
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  ✔️  Current Profit: 0 USD = 0 BNB
  ✔️  Current Balance: 129.075 USD = 0.61207 BNB
  ⏰ Waiting 3.4 minutes before execute SIGNAL_STRATEGY
====================================================================
♻️  Skip round: 216221
🚨 Bot is running in Martingale Mode! Waiting pending rounds: [216220] - if some rounds remain hanging, they will be eliminated after 2 rounds.
====================================================================
⚔️  ROUND: 216222 | ⌚ 16:54 | START 🎉
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  ✔️  Current Profit: 0 USD = 0 BNB
  ✔️  Current Balance: 129.059 USD = 0.61207 BNB
  ⏰ Waiting 3.4 minutes before execute SIGNAL_STRATEGY
====================================================================
♻️  Skip round: 216222
🚨 Bot is running in Martingale Mode! Waiting pending rounds: [216220] - if some rounds remain hanging, they will be eliminated after 2 rounds.
====================================================================
⚔️  ROUND: 216223 | ⌚ 17:00 | START 🎉
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  ✔️  Current Profit: 0 USD = 0 BNB
  ✔️  Current Balance: 128.981 USD = 0.61207 BNB
  ⏰ Waiting 3.4 minutes before execute SIGNAL_STRATEGY
====================================================================
⚔️  ROUND: 216224 | ⌚ 17:05 | START 🎉
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  ✔️  Current Profit: 0 USD = 0 BNB
  ✔️  Current Balance: 128.874 USD = 0.61207 BNB
  ⏰ Waiting 3.4 minutes before execute SIGNAL_STRATEGY
====================================================================
♻️  Skip round: 216224
🚨 Bot is running in Martingale Mode! Waiting pending rounds: [216223] - if some rounds remain hanging, they will be eliminated after 2 rounds.
====================================================================

**Comment by lmusarella** [comment]
NUM_ROUNDS_AFTER_DELETE_PENDING_ROUNDS: 5                    try to use this configuration.

**Comment by tocacyy** [comment]
I've tried this option too, setting it to 5, and it still does the same thing :) It seems to enter into a loop

**Comment by tocacyy** [comment]
I will put it in a screen now and I will post the results here in about an hour

**Comment by lmusarella** [comment]
Is not a loop, when you run the bot in martingale mode you have to wait the pending rounds. If the are pending rounds, cancelled or burn round, After 5 rounds the pending rounds Will be remouved form the stack

**Comment by tocacyy** [comment]
I've been using this final version for about a week, and it worked without any issues. Even when I changed the NUM_ROUNDS_AFTER_DELETE_PENDING_ROUNDS: from 5 to 2, it worked. However, for about 12 hours now it's not working anymore. It waits for the round to finish, as I mentioned above. I also reverted back to the setting of 5, thinking maybe that was the issue, but it still behaves the same way. It waits 5 times, and after it's done, it starts over with the next round. I hope I'm making myself clear :) I'll also provide a screenshot later and the setting on 5.

**Comment by lmusarella** [comment]
Ok, let me know if Is a random problem, or Always happen

Il gio 19 ott 2023, 17:04 Tocacyy ***@***.***> ha scritto:

**Comment by tocacyy** [comment]
⚔️  ROUND: 216240 | ⌚ 18:26 | START 🎉
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  ✔️  Current Profit: 0 USD = 0 BNB
  ✔️  Current Balance: 129.105 USD = 0.61207 BNB
  ⏰ Waiting 3.4 minutes before execute SIGNAL_STRATEGY
====================================================================
♻️  Skip round: 216240
🚨 Bot is running in Martingale Mode! Waiting pending rounds: [216238] - if some rounds remain hanging, they will be eliminated after 5 rounds.
====================================================================
⚔️  ROUND: 216241 | ⌚ 18:31 | START 🎉
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  ✔️  Current Profit: 0 USD = 0 BNB
  ✔️  Current Balance: 129.067 USD = 0.61207 BNB
  ⏰ Waiting 3.4 minutes before execute SIGNAL_STRATEGY
====================================================================
♻️  Skip round: 216241
🚨 Bot is running in Martingale Mode! Waiting pending rounds: [216238] - if some rounds remain hanging, they will be eliminated after 5 rounds.
====================================================================
⚔️  ROUND: 216242 | ⌚ 18:36 | START 🎉
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  ✔️  Current Profit: 0 USD = 0 BNB
  ✔️  Current Balance: 129.122 USD = 0.61207 BNB
  ⏰ Waiting 3.4 minutes before execute SIGNAL_STRATEGY
====================================================================
♻️  Skip round: 216242
🚨 Bot is running in Martingale Mode! Waiting pending rounds: [216238] - if some rounds remain hanging, they will be eliminated after 5 rounds.
====================================================================
⚔️  ROUND: 216243 | ⌚ 18:41 | START 🎉
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  ✔️  Current Profit: 0 USD = 0 BNB
  ✔️  Current Balance: 128.914 USD = 0.61207 BNB
  ⏰ Waiting 3.4 minutes before execute SIGNAL_STRATEGY
====================================================================
♻️  Skip round: 216243
🚨 Bot is running in Martingale Mode! Waiting pending rounds: [216238] - if some rounds remain hanging, they will be eliminated after 5 rounds.
====================================================================
⚔️  ROUND: 216244 | ⌚ 18:46 | START 🎉
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  ✔️  Current Profit: 0 USD = 0 BNB
  ✔️  Current Balance: 128.913 USD = 0.61207 BNB
  ⏰ Waiting 3.4 minutes before execute SIGNAL_STRATEGY
====================================================================
⚔️  ROUND: 216245 | ⌚ 18:51 | START 🎉
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  ✔️  Current Profit: 0 USD = 0 BNB
  ✔️  Current Balance: 128.858 USD = 0.61207 BNB
  ⏰ Waiting 3.4 minutes before execute SIGNAL_STRATEGY
====================================================================
♻️  Skip round: 216245
🚨 Bot is running in Martingale Mode! Waiting pending rounds: [216244] - if some rounds remain hanging, they will be eliminated after 5 rounds.
====================================================================
⚔️  ROUND: 216246 | ⌚ 18:56 | START 🎉
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  ✔️  Current Profit: 0 USD = 0 BNB
  ✔️  Current Balance: 128.85 USD = 0.61207 BNB
  ⏰ Waiting 3.4 minutes before execute SIGNAL_STRATEGY
====================================================================
♻️  Skip round: 216246
🚨 Bot is running in Martingale Mode! Waiting pending rounds: [216244] - if some rounds remain hanging, they will be eliminated after 5 rounds.
====================================================================
⚔️  ROUND: 216247 | ⌚ 19:02 | START 🎉
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  ✔️  Current Profit: 0 USD = 0 BNB
  ✔️  Current Balance: 128.827 USD = 0.61207 BNB
  ⏰ Waiting 3.4 minutes before execute SIGNAL_STRATEGY
====================================================================
♻️  Skip round: 216247
🚨 Bot is running in Martingale Mode! Waiting pending rounds: [216244] - if some rounds remain hanging, they will be eliminated after 5 rounds.
====================================================================
⚔️  ROUND: 216248 | ⌚ 19:07 | START 🎉
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  ✔️  Current Profit: 0 USD = 0 BNB
  ✔️  Current Balance: 128.908 USD = 0.61207 BNB
  ⏰ Waiting 3.4 minutes before execute SIGNAL_STRATEGY
====================================================================
♻️  Skip round: 216248
🚨 Bot is running in Martingale Mode! Waiting pending rounds: [216244] - if some rounds remain hanging, they will be eliminated after 5 rounds.
====================================================================
⚔️  ROUND: 216249 | ⌚ 19:12 | START 🎉
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  ✔️  Current Profit: 0 USD = 0 BNB
  ✔️  Current Balance: 128.948 USD = 0.61207 BNB
  ⏰ Waiting 3.4 minutes before execute SIGNAL_STRATEGY
====================================================================
♻️  Skip round: 216249
🚨 Bot is running in Martingale Mode! Waiting pending rounds: [216244] - if some rounds remain hanging, they will be eliminated after 5 rounds.
====================================================================
⚔️  ROUND: 216250 | ⌚ 19:17 | START 🎉
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  ✔️  Current Profit: 0 USD = 0 BNB
  ✔️  Current Balance: 129.003 USD = 0.61207 BNB
  ⏰ Waiting 3.4 minutes before execute SIGNAL_STRATEGY
====================================================================
⚔️  ROUND: 216251 | ⌚ 19:22 | START 🎉
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  ✔️  Current Profit: 0 USD = 0 BNB
  ✔️  Current Balance: 128.942 USD = 0.61207 BNB
  ⏰ Waiting 3.4 minutes before execute SIGNAL_STRATEGY
====================================================================
♻️  Skip round: 216251
🚨 Bot is running in Martingale Mode! Waiting pending rounds: [216250] - if some rounds remain hanging, they will be eliminated after 5 rounds.
====================================================================
⚔️  ROUND: 216252 | ⌚ 19:27 | START 🎉
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  ✔️  Current Profit: 0 USD = 0 BNB
  ✔️  Current Balance: 128.935 USD = 0.61207 BNB
  ⏰ Waiting 3.4 minutes before execute SIGNAL_STRATEGY
====================================================================
♻️  Skip round: 216252
🚨 Bot is running in Martingale Mode! Waiting pending rounds: [216250] - if some rounds remain hanging, they will be eliminated after 5 rounds.
====================================================================
⚔️  ROUND: 216253 | ⌚ 19:32 | START 🎉
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  ✔️  Current Profit: 0 USD = 0 BNB
  ✔️  Current Balance: 128.963 USD = 0.61207 BNB
  ⏰ Waiting 3.4 minutes before execute SIGNAL_STRATEGY
====================================================================
♻️  Skip round: 216253
🚨 Bot is running in Martingale Mode! Waiting pending rounds: [216250] - if some rounds remain hanging, they will be eliminated after 5 rounds.
====================================================================
⚔️  ROUND: 216254 | ⌚ 19:37 | START 🎉
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  ✔️  Current Profit: 0 USD = 0 BNB
  ✔️  Current Balance: 128.886 USD = 0.61207 BNB
  ⏰ Waiting 3.4 minutes before execute SIGNAL_STRATEGY
====================================================================
♻️  Skip round: 216254
🚨 Bot is running in Martingale Mode! Waiting pending rounds: [216250] - if some rounds remain hanging, they will be eliminated after 5 rounds.
====================================================================
⚔️  ROUND: 216255 | ⌚ 19:42 | START 🎉
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  ✔️  Current Profit: 0 USD = 0 BNB
  ✔️  Current Balance: 128.857 USD = 0.61207 BNB
  ⏰ Waiting 3.4 minutes before execute SIGNAL_STRATEGY
====================================================================
♻️  Skip round: 216255
🚨 Bot is running in Martingale Mode! Waiting pending rounds: [216250] - if some rounds remain hanging, they will be eliminated after 5 rounds.
====================================================================
⚔️  ROUND: 216256 | ⌚ 19:47 | START 🎉
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  ✔️  Current Profit: 0 USD = 0 BNB
  ✔️  Current Balance: 128.991 USD = 0.61207 BNB
  ⏰ Waiting 3.4 minutes before execute SIGNAL_STRATEGY
====================================================================
⚔️  ROUND: 216257 | ⌚ 19:52 | START 🎉
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  ✔️  Current Profit: 0 USD = 0 BNB
  ✔️  Current Balance: 128.975 USD = 0.61207 BNB
  ⏰ Waiting 3.4 minutes before execute SIGNAL_STRATEGY
====================================================================
♻️  Skip round: 216257
🚨 Bot is running in Martingale Mode! Waiting pending rounds: [216256] - if some rounds remain hanging, they will be eliminated after 5 rounds.
====================================================================
⚔️  ROUND: 216258 | ⌚ 19:57 | START 🎉
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  ✔️  Current Profit: 0 USD = 0 BNB
  ✔️  Current Balance: 128.926 USD = 0.61207 BNB
  ⏰ Waiting 3.4 minutes before execute SIGNAL_STRATEGY
====================================================================
♻️  Skip round: 216258
🚨 Bot is running in Martingale Mode! Waiting pending rounds: [216256] - if some rounds remain hanging, they will be eliminated after 5 rounds.
====================================================================
⚔️  ROUND: 216259 | ⌚ 20:03 | START 🎉
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  ✔️  Current Profit: 0 USD = 0 BNB
  ✔️  Current Balance: 128.891 USD = 0.61207 BNB
  ⏰ Waiting 3.4 minutes before execute SIGNAL_STRATEGY
====================================================================
♻️  Skip round: 216259
🚨 Bot is running in Martingale Mode! Waiting pending rounds: [216256] - if some rounds remain hanging, they will be eliminated after 5 rounds.
====================================================================

**Comment by lmusarella** [comment]
Can you paste me, your bot configuration? I Will try It in locale

Il gio 19 ott 2023, 19:09 Tocacyy ***@***.***> ha scritto:

**Comment by tocacyy** [comment]
I tried it with MARTINGALE Off and it still does the same thing. I have no choice but to change the wallet from which I am betting; maybe I got banned :))

const GLOBAL_CONFIG = {
    /**
     * Defines the type of Prediction Game used by the bot (BNB-USDT or CAKE-USDT)
     * @values BNB | CAKE
     * @mandatory
     * @default BNB
     * @type {string}
     */
    PCS_CRYPTO_SELECTED: 'BNB',
    /**
     * Flag which enables the simulation mode of bot. The bot in simulated mode does not make any transactions towards the smart contracts, 
     * the calculation of the profits/win/loss is performed with a fake balance.
     * @default true
     * @type {boolean}
     */
    SIMULATION_MODE: false,
    ANALYTICS_CONFIGURATION: {
        /**
         * Flag which enables to save users activity in history
         * @default false
         * @type {boolean}
         */
        REGISTER_USERS_ACTIVITY: true,
        /**
         * Flag which enables to save all rounds data
         * @default false
         * @type {boolean}
         */
        REGISTER_ALL_ROUNDS_DATA: true,
         /**
         * Flag which enables to save current bot-history data in backup folders e and clean the previus data folders for new bot run cicle
         * @default false
         * @type {boolean}
         */
        RESET_AND_BACKUP_BOT_HISTORY: true
    },
    SIMULATION_CONFIGURATION: {
        /**
        * Fake balance used in simulation mode
        * @default 50
        * @type {number}
        */
        SIMULATION_BALANCE: 5000, // in USD
        /**
         * Calculate the gas fee in simulation mode use this params for estimate gas functions (betBull, betBear, claim)
         * @default 90000
         * @type {number}
         */
        SIMULATE_ESTIMATE_GAS: 90000, // Based on 0.5 USD value amount
    },
    BET_CONFIGURATION: {
        /**
         * Defines the amount to be paid in dollars for each bet
         * @default 1
         * @type {number}
         */
        BET_AMOUNT: 0.25, // in USD
        /**
         * Defines the daily goal, if is reached the bot will stop
         * @default 50
         * @type {number}
         */
        DAILY_GOAL: 500, // in USD
        /**
         * Defines the stop loss, if is reached the bot will stop
         * @default 50
         * @type {number}
         */
        STOP_LOSS: 1000, // in USD
        MARTINGALE_CONFIG: {
             /**
             * Flag that enabled Martingale/Anti-Martingale bet strategy
             * @default false
             * @type {boolean}
             */
            ACTIVE: true, 
             /**
             * Increment BetAmount after loss if FALSE, Increment BetAmount after Win if TRUE
             * @default false
             * @type {boolean}
             */
            ANTI_MARTINGALE: false, 
             /**
             * INCREMENT_BET_AMOUNT x BET_AMOUNT = NEW BET_AMOUNT after loss or win (based on ANTI_MARTINGALE flag)
             * @default 2
             * @type {number}
             */
            INCREMENT_BET_AMOUNT: 2,
             /**
             * After how many rounds will the suspended rounds be eliminated, because of PancakeSwap can burn/delete some rounds, which will never be completed, remaining in the hanging rounds stack
             * @default 5
             * @type {number}
             */
            NUM_ROUNDS_AFTER_DELETE_PENDING_ROUNDS: 5                    
        }
    },
    STRATEGY_CONFIGURATION: {
        /**
         * Defines the type of betting strategy used by the bot
         * - SIGNAL_STRATEGY: get trading signals from TradingViewScan and use recommended signal for UP or DOWN prediction
         * - QUOTE_STRATEGY: chose the lower or the highiest quote from PCS smart-contract payout quote for UP or DOWN prediction
         * - COPY_TRADING_STRATEGY: copy an address bet operations (Bet Bull or Bet Bear) on PCS game prediction
         * @values SIGNAL_STRATEGY | QUOTE_STRATEGY | COPY_TRADING_STRATEGY | PATTERN_STRATEGY
         * @mandatory
         * @default SIGNAL_STRATEGY
         * @type {string}
         */
        SELECTED_STRATEGY: 'SIGNAL_STRATEGY',
        /**
         * Time after execute bet strategy when start a new round.
         * @default 265000 in Miliseconds (4.3 Minutes)
         * @type {number}
         */
        WAITING_TIME: 265000,
        /**
        * Flag which enables the automatic claim of bet winnings after each bet won
        * @default true
        * @type {boolean}
        */
        CLAIM_REWARDS: true,
        SIGNAL_STRATEGY: {
            /**
             * Flag which enables the reverse bet strategy (only for signals) if signals recommend to bet up, the bot bet down
             * @default false
             * @type {boolean}
             */
            REVERSE_BETTING: true,
             /**
             * Defines the minimum percentage threshold of signal accuracy (50% - 100%)
             * @default 55
             * @type {number}
             */
            THRESHOLD: 49,
             /**
             * Datasoure of the trading signals library
             * @default BINANCE
             * @type {string}
             */
            DATASOURCE: "BINANCE"
        },
        QUOTE_STRATEGY: {
             /**
             * Flag which enables to Bet on the lowe or highest quote from Pancakeswap prediction
             * @default false
             * @type {boolean}
             */
            SELECT_LOWER_QUOTE: false       
        },
        COPY_TRADING_STRATEGY: {
             /**
             * Wallet address to emulate, Emulate the actions of this address on Pancakeswap prediction game        
             * @type {string}
             */
            WALLET_ADDRESS_TO_EMULATE: '0xe25E5Db92Ad947c89015f085fD830823F3cF2fB8'
        },
        PATTERN_STRATEGY: {
            /**
            * Defines the number of previous rounds having the same outcome, the bot will bet the next round towards the opposite sign.     
            * @type {number}
            */
           EVENT_PATTERN_NUMBER: 2,
            /**
            * To more accurately predict the outcome of the round that is about to end, a larger price difference will be statistically easier to predict. 
            * So define your threshold and only if respected the correct round will be considered in the pattern. 
            * Example: If when I retrieve the current price and the difference with the opening price is 0.3 or -0.3 it will be more likely to respect the outcome than a difference of 0.003 or -0.003.
            * However, if during the last few seconds the volatility is high, you can increase the WAITING_TIME parameter  
            * @type {number}
            */
           DELTA_PRICE_THRESHOLD: 0.2
       }
    }
};

module.exports = {
    GLOBAL_CONFIG
};

**Comment by tocacyy** [comment]
That's exactly what I thought. After moving the funds to another wallet, it now works without any issues. The wallet was banned by the PancakeSwap :))
