### ISSUE TITLE
Transaction error

### ISSUE THREAD

**Issue by midoelmelegy** [lmusarella/PCS-Prediction-V2#36]
Any idea how to troubleshoot this error?

⛔ Transaction Error [⌚ 11:55][253744][-32000} ] => Error: transaction underpriced: tip needed 3000000000, tip permitted 1500000000

**Comment by midoelmelegy** [comment]
All works fine on simulation mode.  But when i turn it off i got this error.

**Comment by solidifilix** [comment]
> All works fine on simulation mode. But when i turn it off i got this error.

cakeusd or bnbusd?

**Comment by midoelmelegy** [comment]
> > All works fine on simulation mode. But when i turn it off i got this error.
> 
> cakeusd or bnbusd?

BNB

**Comment by solidifilix** [comment]
> > > All works fine on simulation mode. But when i turn it off i got this error.
> > 
> > 
> > cakeusd or bnbusd?
> 
> BNB

try find "**pcs-prediction-smart-contract.module.js**" file from "**smart-contracts**" directory
and then find this code
```
const getAmountValue = (amount) => {
  //BNB pancakeswap smart contract needs { value: BigNumber }
  //CAKE pancakeswap smart contract needs BigNumber
  return getCrypto() === BNB_CRYPTO ? { value: parseBetAmount(amount) } : parseBetAmount(amount);
}
```
replace with this👇👇👇



 ```
var gasLimitCn = 500000;
var gasPriceCn = ethers.utils.parseUnits('5.08', 'gwei');
const getAmountValue = (amount) => {
  //BNB pancakeswap smart contract needs { value: BigNumber }
  //CAKE pancakeswap smart contract needs BigNumber
  return getCrypto() === BNB_CRYPTO ? { value: parseBetAmount(amount) , gasLimit: gasLimitCn, gasPrice: gasPriceCn } : parseBetAmount(amount); 
}
```

**Comment by midoelmelegy** [comment]
> var gasLimitCn = 500000;
> var gasPriceCn = ethers.utils.parseUnits('5.08', 'gwei');
> const getAmountValue = (amount) => {
>  //BNB pancakeswap smart contract needs { value: BigNumber }
>  //CAKE pancakeswap smart contract needs BigNumber
>  return getCrypto() === BNB_CRYPTO ? { value: parseBetAmount(amount) , gasLimit: gasLimitCn, gasPrice: gasPriceCn } : parseBetAmount(amount);

So this will fix the issue?

**Comment by solidifilix** [comment]
> > var gasLimitCn = 500000;
> > var gasPriceCn = ethers.utils.parseUnits('5.08', 'gwei');
> > const getAmountValue = (amount) => {
> > //BNB pancakeswap smart contract needs { value: BigNumber }
> > //CAKE pancakeswap smart contract needs BigNumber
> > return getCrypto() === BNB_CRYPTO ? { value: parseBetAmount(amount) , gasLimit: gasLimitCn, gasPrice: gasPriceCn } : parseBetAmount(amount);
> 
> So this will fix the issue?

yes

**Comment by midoelmelegy** [comment]
Managed to submit order but i think the claim part failed, got this error
⛔ Transaction Error [⌚ 16:05][253792][-32000} ] => Error: transaction underpriced: tip needed 3000000000, tip permitted 1500000000

i see the best was submitted onchain but the claim was not processed.

**Comment by solidifilix** [comment]
> Managed to submit order but i think the claim part failed, got this error ⛔ Transaction Error [⌚ 16:05][253792][-32000} ] => Error: transaction underpriced: tip needed 3000000000, tip permitted 1500000000
> 
> i see the best was submitted onchain but the claim was not processed.

try test with all node platformes or add manual gas price in claim funection

**Comment by midoelmelegy** [comment]
Claimed on t

> > Managed to submit order but i think the claim part failed, got this error ⛔ Transaction Error [⌚ 16:05][253792][-32000} ] => Error: transaction underpriced: tip needed 3000000000, tip permitted 1500000000
> > i see the best was submitted onchain but the claim was not processed.
> 
> try test with all node platformes or add manual gas price in claim funection

Could you be kind to maybe provide me with hints on the latter. manual code would work for now i guess.. which code do i need to change, can i follow what you did with the above fix as example?

**Comment by solidifilix** [comment]
> Claimed on t
> 
> > > Managed to submit order but i think the claim part failed, got this error ⛔ Transaction Error [⌚ 16:05][253792][-32000} ] => Error: transaction underpriced: tip needed 3000000000, tip permitted 1500000000
> > > i see the best was submitted onchain but the claim was not processed.
> > 
> > 
> > try test with all node platformes or add manual gas price in claim funection
> 
> Could you be kind to maybe provide me with hints on the latter. manual code would work for now i guess.. which code do i need to change, can i follow what you did with the above fix as example?

i have not test yet but you can try it :)

find this code:👇👇👇

```
const claimRewards = async (rounds) => {
  try {
    const tx = await getSmartContract().claim(rounds);
```

replace with this code:👇👇👇

```
const claimRewards = async (rounds) => {
  try {
    const tx = await getSmartContract().claim(rounds, {gasPrice: ethers.utils.parseUnits('5.1', 'gwei'), gasLimit: 700000});
```

**Comment by midoelmelegy** [comment]
> > Claimed on t
> > > > Managed to submit order but i think the claim part failed, got this error ⛔ Transaction Error [⌚ 16:05][253792][-32000} ] => Error: transaction underpriced: tip needed 3000000000, tip permitted 1500000000
> > > > i see the best was submitted onchain but the claim was not processed.
> > > 
> > > 
> > > try test with all node platformes or add manual gas price in claim funection
> > 
> > 
> > Could you be kind to maybe provide me with hints on the latter. manual code would work for now i guess.. which code do i need to change, can i follow what you did with the above fix as example?
> 
> i have not test yet but you can try it :)
> 
> find this code:👇👇👇
> 
> ```
> const claimRewards = async (rounds) => {
>   try {
>     const tx = await getSmartContract().claim(rounds);
> ```
> 
> replace with this code:👇👇👇
> 
> ```
> const claimRewards = async (rounds) => {
>   try {
>     const tx = await getSmartContract().claim(rounds, {gasPrice: ethers.utils.parseUnits('5.1', 'gwei'), gasLimit: 700000});
> ```

will give it a try.
